# Generated by Django 5.0.6 on 2024-08-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=' ', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
